# Generated by Django 6.0.7 on 2026-07-13 13:02

import apps.access_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_remove_schedule_day_of_week_schedule_friday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_token',
            field=models.CharField(db_index=True, default=apps.access_control.models.generate_api_token, max_length=64, unique=True),
        ),
    ]
