# Generated by Django 6.0.7 on 2026-07-13 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_device_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='uid',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Card UID must be a valid hexadecimal string of length 8 to 32 characters (4 to 16 bytes).', regex='^[0-9A-F]{8,32}$')]),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Device ID must contain only letters, numbers, underscores, or hyphens.', regex='^[a-zA-Z0-9_-]+$')]),
        ),
    ]
