# Generated by Django 4.2.30 on 2026-07-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=50)),
                ('card_uid', models.CharField(db_index=True, max_length=50)),
                ('authorized', models.BooleanField()),
                ('user_details', models.CharField(max_length=200)),
            ],
        ),
    ]
