# Generated by Django 6.0.7 on 2026-08-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('PASSWORD_CHANGED', 'Password Changed'), ('ROLE_CHANGED', 'Role / Permissions Changed'), ('IP_BLOCKED', 'IP Address Blocked'), ('IP_UNBLOCKED', 'IP Address Unblocked'), ('SESSION_EXPIRED', 'Session Expired (Inactivity / Max Age)')], db_index=True, max_length=50)),
                ('actor', models.CharField(blank=True, max_length=150, null=True)),
                ('target_user', models.CharField(blank=True, max_length=150, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
            ],
        ),
    ]
